### ISSUE TITLE
.Batch() is required in r2016.02.04?

### ISSUE THREAD

**Issue by zygis** [go-mgo/mgo#219] opened 2016-02-08 06:38 UTC
Error I receive:
```
Batch size for getMore must be positive, but received: 0
```

**Comment by mvader** [comment] 2016-02-08 14:20
I have experienced this issue too

**Comment by niemeyer** [comment] 2016-02-08 22:30
There were major internal changes on how these settings are reported to the server due to new server requirements, but the behavior should still be the same or that's s bug I want to fix.

Do you have a small snippet reproducing the issue?

Meanwhile, I'll be trying a few guesses to see if I can reproduce it locally.

**Comment by niemeyer** [comment] 2016-02-09 01:59
This has been tested, fixed, and released with d90005c.

I'm sorry for the trouble!

**Closed by niemeyer** 2016-02-09 01:59 UTC
