### ISSUE TITLE
Improve bulk error handling

### ISSUE THREAD

**Issue by pjebs** [go-mgo/mgo#189] opened 2015-11-23 04:20 UTC
Other mongo drivers for other languages allow us to determine which bulk inserts suceeded and which failed.

The best we can do with mgo is receive an amalgamated string which we must manually parse.

It would be good if we can inspect the QueryError struct ourself.

`
err: &mgo.bulkError{errs:[]error{(*mgo.QueryError)(0xc20801f2e0), (*mgo.QueryError)(0xc20801f300), (*mgo.QueryError)(0xc20801f340)}}
`

**Comment by pjebs** [comment] 2015-11-23 05:04
Even better, would you be able to replicate the node.js library which tells you the full contents of the inserts that succeeded and failed. That way, we can identify exactly which insert needs to be reapplied.

**Comment by niemeyer** [comment] 2015-11-23 09:15
We're definitely heading there. If you see the progression of the bulk API over the last few releases, you'll see how the error handling is improving over time. We're not quite there yet, and the reason why errs isn't exported today is precisely because we know there are improvements coming that will break your code if you just look at an exported version of errs right now.

Can you please let me know what is the actual problem you're trying to solve today, rather than how you'd like to see it solved?  This will help me while designing the proper interface to export.

Thanks for your help and patience.

**Comment by pjebs** [comment] 2015-11-23 11:25
I just need a way to determine which Inserts potentially failed and which succeeded (in a bulk insert).
If you can tell me a good way, that would be awesome. That way, I can create a private fork temporarily until it's sorted in this package.

**Comment by pjebs** [comment] 2015-11-23 12:05
I don't mind if its a messy solution either.

**Comment by niemeyer** [comment] 2015-11-23 15:18
For that we'll probably need an index so that you can relate the error to the position of the insert in the argument list. Either that, or we use a slice of matching size with corresponding errors, and fill it up with nils where we know it worked.

Either of these needs to be artificially constructed. When a slice is broken up into multiple commands to not exceed the maximum number of elements per command, and also when talking to an old servers which does not support the bulk operation at hand (e.g. bulk update on 2.2), we need to consolidate errors into the same set appropriately.

**Comment by pjebs** [comment] 2015-11-23 19:41
Thanks for the suggestion.
Can you please clarify what you mean. I am struggling to understand your solution and how it relates currently to the err return from the bulk.insert() function

**Comment by niemeyer** [comment] 2015-11-23 20:13
Perhaps the best path forward is for me to implement something and see whether it works for you. It'd be a useful exercise for me as well as it'd be good basis for whether the API is right.

**Comment by pjebs** [comment] 2015-11-23 21:22
Keep in mind:
`
result, err := b.Run()
`

err is of type `&mgo.bulkError` which is not exported.
Hence you only get access to to the `.Error()` message.

Typical error messages look like this:
`
err: multiple errors in bulk operation:
		  - insertDocument :: caused by :: 11000 E11000 duplicate key error index: t.locations.$journey_id_1_sync_id_1  dup key: { : ObjectId('56511aed72b2c003fd302e5b'), : "1245555588" }
		  - insertDocument :: caused by :: 11000 E11000 duplicate key error index: t.locations.$journey_id_1_sync_id_1  dup key: { : ObjectId('56511aed72b2c003fd302e5b'), : "01244555" }
		  - insertDocument :: caused by :: 11000 E11000 duplicate key error index: t.locations.$journey_id_1_sync_id_1  dup key: { : ObjectId('56511aed72b2c003fd302e5b'), : "012455115" }
		  - insertDocument :: caused by :: 11000 E11000 duplicate key error index: t.locations.$journey_id_1_sync_id_1  dup key: { : ObjectId('56511aed72b2c003fd302e5b'), : "233251214555" }
		  - insertDocument :: caused by :: 11000 E11000 duplicate key error index: t.locations.$journey_id_1_sync_id_1  dup key: { : ObjectId('56511aed72b2c003fd302e5b'), : "01234555" }
`

**Comment by niemeyer** [comment] 2015-11-23 21:23
Right, both of these points are as designed.

**Comment by pjebs** [comment] 2015-11-23 21:28
That's why I didn't understand your previous solution.
You mentioned linking the position of the argument in the insert() to the error message. Wasn't sure how to link it without possibly parsing the string line by line and looking for "ObjectId('XXXX')"

**Comment by pjebs** [comment] 2015-12-01 04:43
Hi @niemeyer 
I was wondering if you had worked out a solution to this? Would the package have to be totally restructured?

**Comment by pjebs** [comment] 2016-01-03 20:04
Is there anything I can do to help out with this issue?

**Comment by niemeyer** [comment] 2016-01-06 15:37
No solutions yet, but I'll try to have something in the unstable branch soon.

**Comment by pjebs** [comment] 2016-01-13 14:17
Any estimate on when this will be implemented? In a few months?

For the time being, should I just do single inserts concurrently? Would each goroutine performing the insert have to use session.Copy()? Not sure of how the connections to database work behind the scenes.

**Comment by niemeyer** [comment] 2016-01-13 14:28
This should be landed in unstable today still. It's surprisingly tricky to get right due to the need to map an the order in which operations are added (the visible order) and the multiple ways the individual operations are manipulated to satisfy the several server versions.

**Comment by pjebs** [comment] 2016-01-13 14:43
In mongo you can do ordered inserts and unordered inserts. Will your solution force ordered inserts which are not done in parallel.

**Comment by niemeyer** [comment] 2016-01-13 15:05
Whether ordered or unordered inserts are not done in parallel. The solution will use what the server offers, which in old servers can mean not being able to identify the proper error index, for example.

**Comment by pjebs** [comment] 2016-01-14 01:18
Is there any way to `go get -u` from the unstable branch?

**Closed** 2016-01-18 14:38 UTC
