### ISSUE TITLE
how i connect mongodb

### ISSUE THREAD

**Issue by guojun1992** [go-mgo/mgo#188] opened 2015-11-23 03:17 UTC
hi,I used mgo recently,
the command I can connect mongo server

mongo --port 6879 -uadmin  -pOshrawdOs2 admin
MongoDB shell version: 3.0.7
connecting to: 127.0.0.1:6879/admin

I wrote in golang 
session, err := mgo.DialWithTimeout("mongodb://admin:OshrawdOs2@localhost:6879/admin", time.Duration(this.timeout)*time.Millisecond)

but I can not conncect mongo ,how can I do?

thanks

**Comment by guojun1992** [comment] 2015-11-23 03:19
with the panic log 

panic: auth failed

**Comment by webgini** [comment] 2015-11-23 05:14
https://docs.compose.io/languages/golang.html check this out @guojun1992 , and please close this issue.

**Comment by guojun1992** [comment] 2015-11-23 06:48
@webgini I can not check out any error from my mongodbURL,can you tell me？i used mongodb 3.0.7, now I will use mongodb 2.6.

**Comment by niemeyer** [comment] 2015-11-23 09:19
What do the server logs say when you try to connect with mgo?

**Comment by guojun1992** [comment] 2015-11-23 09:29
panic:auth failed     always

**Comment by niemeyer** [comment] 2015-11-23 09:35
That's not a line from the server logs.

**Comment by guojun1992** [comment] 2015-11-23 09:43
Server Exit
panic: auth failed

goroutine 1 [running]:
OSUCSession/src/models.(*Mongo).Init(0x8ea1e0, 0xc208030187, 0x29, 0x3e8, 0x1)
        /home/guojun-s/goSpace/src/OSUCSession/src/models/Mongo.go:29 +0xc7
main.envInit()
        /home/guojun-s/goSpace/src/OSUCSession/main.go:35 +0x462
main.main()
        /home/guojun-s/goSpace/src/OSUCSession/main.go:19 +0x35

goroutine 5 [sleep]:
labix.org/v2/mgo.(*mongoCluster).syncServersLoop(0xc20800c0f0)
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/cluster.go:342 +0x291
created by labix.org/v2/mgo.newCluster
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/cluster.go:72 +0x1d0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [runnable]:
net.(*pollDesc).Wait(0xc208010290, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010290, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010230, 0xc20800b020, 0x24, 0x24, 0x0, 0x7ff4bc089bb8, 0xc20802bbc0)
        /usr/local/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc20803c060, 0xc20800b020, 0x24, 0x24, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xdc
labix.org/v2/mgo.fill(0x7ff4bc089f68, 0xc20803c060, 0xc20800b020, 0x24, 0x24, 0x0, 0x0)
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/socket.go:489 +0x75
labix.org/v2/mgo.(*mongoSocket).readLoop(0xc20807c1c0)
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/socket.go:506 +0x126
created by labix.org/v2/mgo.newSocket
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/socket.go:163 +0x3d3

goroutine 9 [sleep]:
labix.org/v2/mgo.(*mongoServer).pinger(0xc20807c0e0, 0x1)
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/server.go:284 +0x15f
created by labix.org/v2/mgo.newServer
        /home/guojun-s/goSpace/src/labix.org/v2/mgo/server.go:87 +0x196
~                                                                                                                                                                                  
~

**Comment by niemeyer** [comment] 2015-11-23 11:10
These are still not the _MongoDB server logs_ ...

**Comment by guojun1992** [comment] 2015-11-23 11:19
hi,I am wrong,I think you need golang server log


2015-11-23T11:53:30.241+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19591 #27 (1 connection now open)
2015-11-23T11:53:30.242+0800 I ACCESS   [conn27]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "admin", key: "xxx" }
2015-11-23T11:53:30.242+0800 I ACCESS   [conn27] Failed to authenticate admin@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
2015-11-23T11:53:30.243+0800 I NETWORK  [conn27] end connection 127.0.0.1:19591 (0 connections now open)
2015-11-23T11:54:06.154+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19592 #28 (1 connection now open)
2015-11-23T11:54:06.155+0800 I ACCESS   [conn28]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "admin", key: "xxx" }
2015-11-23T11:54:06.155+0800 I ACCESS   [conn28] Failed to authenticate admin@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
2015-11-23T11:54:06.156+0800 I NETWORK  [conn28] end connection 127.0.0.1:19592 (0 connections now open)
2015-11-23T11:55:08.889+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19595 #29 (1 connection now open)
2015-11-23T11:55:08.890+0800 I ACCESS   [conn29]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "admin", key: "xxx" }
2015-11-23T11:55:08.890+0800 I ACCESS   [conn29] Failed to authenticate admin@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
2015-11-23T11:55:08.891+0800 I NETWORK  [conn29] end connection 127.0.0.1:19595 (0 connections now open)
2015-11-23T12:11:30.840+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19618 #30 (1 connection now open)
2015-11-23T12:11:30.859+0800 I ACCESS   [conn30] Successfully authenticated as principal admin on admin
2015-11-23T12:11:30.860+0800 I ACCESS   [conn30] Unauthorized not authorized on admin to execute command { getLog: "startupWarnings" }
2015-11-23T12:11:30.860+0800 I ACCESS   [conn30] Unauthorized not authorized on admin to execute command { replSetGetStatus: 1.0, forShell: 1.0 }
2015-11-23T12:11:38.811+0800 I NETWORK  [conn30] end connection 127.0.0.1:19618 (0 connections now open)
2015-11-23T12:30:54.399+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19644 #31 (1 connection now open)
2015-11-23T12:30:54.418+0800 I ACCESS   [conn31] Successfully authenticated as principal admin on admin
2015-11-23T12:30:54.419+0800 I ACCESS   [conn31] Unauthorized not authorized on admin to execute command { getLog: "startupWarnings" }
2015-11-23T12:30:54.419+0800 I ACCESS   [conn31] Unauthorized not authorized on admin to execute command { replSetGetStatus: 1.0, forShell: 1.0 }
2015-11-23T12:30:57.756+0800 I NETWORK  [conn31] end connection 127.0.0.1:19644 (0 connections now open)
2015-11-23T13:06:43.407+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19689 #32 (1 connection now open)
2015-11-23T13:06:43.425+0800 I ACCESS   [conn32] Successfully authenticated as principal admin on admin
2015-11-23T13:06:43.426+0800 I ACCESS   [conn32] Unauthorized not authorized on admin to execute command { getLog: "startupWarnings" }
2015-11-23T13:06:43.427+0800 I ACCESS   [conn32] Unauthorized not authorized on admin to execute command { replSetGetStatus: 1.0, forShell: 1.0 }
2015-11-23T13:06:44.587+0800 I NETWORK  [conn32] end connection 127.0.0.1:19689 (0 connections now open)
2015-11-23T13:58:12.488+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:19754 #33 (1 connection now open)
2015-11-23T13:58:12.507+0800 I ACCESS   [conn33] Successfully authenticated as principal admin on admin
2015-11-23T13:58:12.508+0800 I ACCESS   [conn33] Unauthorized not authorized on admin to execute command { getLog: "startupWarnings" }
2015-11-23T13:58:12.509+0800 I ACCESS   [conn33] Unauthorized not authorized on admin to execute command { replSetGetStatus: 1.0, forShell: 1.0 }
2015-11-23T13:58:14.420+0800 I NETWORK  [conn33] end connection 127.0.0.1:19754 (0 connections now open)
2015-11-23T17:43:42.715+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:20073 #34 (1 connection now open)
2015-11-23T17:43:42.716+0800 I ACCESS   [conn34]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "admin", key: "xxx" }
2015-11-23T17:43:42.716+0800 I ACCESS   [conn34] Failed to authenticate admin@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
2015-11-23T17:43:42.718+0800 I NETWORK  [conn34] end connection 127.0.0.1:20073 (0 connections now open)
2015-11-23T18:54:24.012+0800 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:20288 #35 (1 connection now open)
2015-11-23T18:54:24.013+0800 I ACCESS   [conn35]  authenticate db: admin { authenticate: 1, nonce: "xxx", user: "admin", key: "xxx" }
2015-11-23T18:54:24.013+0800 I ACCESS   [conn35] Failed to authenticate admin@admin with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document
2015-11-23T18:54:24.015+0800 I NETWORK  [conn35] end connection 127.0.0.1:20288 (0 connections now open)

**Comment by niemeyer** [comment] 2015-11-23 13:31
It looks like the database is not setup in a way that is prepared to authenticate in the way you are trying to authenticate. Note that the server is specifically complaining that the attempt to authenticate with MONGODB-CR is failing because the server doesn't have the proper data in the user document.

The fact you can authenticate with the mongo shell most likely means that the server and the client are in sync about what to expect, but the mgo driver was installed independently from those and may be using a more recent (or older convention, if you are using too old a driver).

Please do the following:

1. Update the mgo driver to the latest version available in gopkg.in/mgo.v2
2. Create a tiny self-contained reproducer and exact instructions for how the server is being run, so I can replicate the problem here. There should be no hidden or implied steps.

Once you have it, please attach the reproducer to this ticket and reopen the ticket.

**Closed by niemeyer** 2015-11-23 13:31 UTC
