### ISSUE TITLE
client continually calling isMaster

### ISSUE THREAD

**Issue by wgallagher** [go-mgo/mgo#254] opened 2016-04-15 15:44 UTC
I'm seeing an issue where, after running for some time in production, the mgo client begins calling authenticate for every query.  This happens after ~ 2 hours at ~ 700RPS.  Once the client enters this state, it never recovers.

When the process first starts, each query is sent using the credentials that were previously authenticated on the socket.  The sequence looks like this:  authenticate, query, logout, authenticate, query, ...  The authentication optimization in auth.go causes the (logout, authenticates) to cancel out producing a sequence of queries:  authenticate, query, query, query, ...

At some point, the client begins to send 'ismaster' before every request.  This breaks that above sequence which now looks like:  authenticate, query, logout, ismaster, authenticate, query, logout.

I believe the cause for the additional 'ismaster' queries is a socket that has been abended due to a recoverable error (timeout?).  The socket abend causes the server to become abended.  This results in the following code from cluster.go to perform a 'ismaster':

		if abended && !slaveOk {
			var result isMasterResult
			err := cluster.isMaster(s, &result)
			if err != nil || !result.IsMaster {
				logf("Cannot confirm server %s as master (%v)", server.Addr, err)
				s.Release()
				cluster.syncServers()
				time.Sleep(100 * time.Millisecond)
				continue

The server.abended state is never reset to 'false' in this case causing each request to be preceeded by an 'ismaster' query and the associated authenticate / logout described above.  The end result is 5 operations being performed for each query.

**Comment by niemeyer** [comment] 2016-04-18 20:45
Thanks for this report. I'll have a look into it.

I see you also pushed some code up to a fork. Did you manage to produce a test case?

**Comment by wgallagher** [comment] 2016-04-18 20:47
I've only been able to reproduce in production after several hours.  I'm still trying to come up with a test case.

**Comment by niemeyer** [comment] 2016-04-18 21:15
I see, thank you. I'll have a look nevertheless, and please let me know if you do come up with a test case.

**Comment by niemeyer** [comment] 2016-05-19 15:31
Closing for the time being. Please reopen if you find out more details.

**Closed by niemeyer** 2016-05-19 15:31 UTC

**Comment by nikhilm** [comment] 2016-10-14 20:29
@niemeyer  This is a reproducible test case - https://gist.github.com/nikhilm/ce59ad89bbf4f2dde53db6c90cc9c447

We are hitting this case consistently in our prod database, where after one socket failure, all sockets in the pool will keep performing extra ismaster checks until we restart our service.

#255 does fix it, but I don't understand enough about mgo internals to know if that is the right fix (especially the locking).

I hope the test case works, I only have about a 80% success rate with it running against a local mongo.

cc @vlopatkin

**Comment by domodwyer** [comment] 2017-03-29 09:39
We experienced this issue during high-load tests in staging this week (nearly a year since this bug was reported). Throughput in our case dropped from around 12,000 op/s to 700 op/s and we confirmed the `isMaster->authenticate->query->logout` cycle using tcpdump.

#255 has fixed the issue for me and seems like a very light weight change, well worth a merge given the performance penalty of this bug - thanks @wgallagher for the PR.

**Comment by JeffreyDing11223** [comment] 2018-04-13 08:06
#403
