### ISSUE TITLE
mgo/txn: one bad transaction can break the queue

### ISSUE THREAD

**Issue by rogpeppe** [go-mgo/mgo#98] opened 2015-05-11 18:07 UTC
If a transaction is phrased badly, it can get stuck in the queue
and poison it so that no further progress can be made.

Code to demonstrate the issue here: http://play.golang.org/p/50-su169eu

The first update transaction gets a "Modifiers and non-modifiers cannot be mixed"
error (itself something that I would not have expected).

Any subsequent operations fail with the same error - the queue is now stuck.

**Comment by niemeyer** [comment] 2015-05-11 18:18
What do you suggest we do in those cases?  Simply ignoring the error seems pretty bad.

**Comment by jameinel** [comment] 2015-05-11 18:58
There was a small typo in Roger's original comment: http://play.golang.org/p/fgma7ldryU

I think the issue is that how do you get out of this situation? The ideal situation would be that you would be unable to apply the second Transaction and it would get rejected. Put I guess the issue is that there are no invalid Assertions, right? Is there a way, after the fact, to mark a transaction as failed so you can purge it from the queue?

**Comment by niemeyer** [comment] 2015-05-11 19:05
If you mark the transaction as aborted, it should stop trying to execute it. I don't think we can do that automatically, though. The key difficulty in this scenario is that the transaction was _already_ executing, and most likely partly applied (unless it was the very first op). So "rejecting" it actually means leaving it behind partly applied, which is exactly what the txn package tries hard to avoid. I'm afraid to say that the only sane way to get out of this situation is by analyzing what broke, making sure the partly applied transaction didn't break anything, and then flagging it as indicated.

**Comment by niemeyer** [comment] 2015-05-12 15:56
Closing on that basis for the time being. Please feel free to include further feedback.

**Closed by niemeyer** 2015-05-12 15:56 UTC
